# Use an official MySQL image as a parent image
FROM mysql:5.7

# Copy the initialization script into the container at /docker-entrypoint-initdb.d/
COPY init.sql /docker-entrypoint-initdb.d











