version: "3.2"

services:
  app:
    build: .
    command: sh -c "sleep 10s ; python app.py"
    container_name: "flask-app"
    ports:
      - "5000:5000"
    depends_on:
      - db
      - model

  db:
    build:
      context: ./mysql
    restart: always
    container_name: "mysqldb"
    environment:
         MYSQL_ROOT_PASSWORD: "root"
         MYSQL_DATABASE: "imageClassifier"
         MYSQL_HOST: "localhost"
         MYSQL_USER: "root"
         MYSQL_PASSWORD: "root"
    ports:
       - "3307:3306"
    volumes:
       - ./db:/docker-entrypoint-initdb.d/:ro
  

  model:
    build:
      context: ./model
    container_name: "modelcontainer"
