version: "3.7"

services:
  app:
    build: .
    container_name: "flask-app"
    ports:
      - "5000:5000"
    depends_on:
      - db
      - model

  db:
    build:
      context: ./mysql
    container_name: "mysql-db"

  model:
    build:
      context: ./model
    container_name: "model-container"

